project:
  type: website

website:
  title: "Nath"
  navbar:
    left:
      - text: Home
        href: index.qmd
     

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



